Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2018-10, with the labels that each got.

#3 add Makefile
  Dockerfile
  Makefile
  cmd/descheduler-operator/main.go
  pkg/stub/handler.go
Labels: size/S

#4 Update install.sh to work with olm based csv
  hack/install.sh
Labels: size/XS

#5 change image path to ci built image
  deploy/olm-catalog/csv.yaml
  deploy/operator.yaml
  pkg/stub/handler.go
Labels: approved, lgtm, size/S

#6 Fix descheduler binary path
  pkg/stub/handler.go
Labels: approved, size/XS
