Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2020-06, with the labels that each got.

#73 Update Dockerfile.rhel7 to golang 1.13
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#109 Bump master to version 4.6
  manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml
  manifests/4.6/image-references
  manifests/4.6/kube-descheduler-operator.crd.yaml
  manifests/4.6/kube-system-rolebinding.yaml
  manifests/cluster-kube-descheduler-operator.package.yaml
Labels: approved, lgtm

#113 bug 1842853: csv: set minKubeVersion to 1.18 to reflect vendored k8s libraries
  manifests/4.5/cluster-kube-descheduler-operator.v4.5.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, group-lead-approved, lgtm

#112 [release-4.4] Bug 1808165: bump(golang.org/x/crypto)
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/cryptobyte/string.go
  vendor/golang.org/x/crypto/poly1305/bits_compat.go
  vendor/golang.org/x/crypto/poly1305/bits_go1.13.go
  vendor/golang.org/x/crypto/poly1305/poly1305.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/poly1305/sum_arm.go
  vendor/golang.org/x/crypto/poly1305/sum_arm.s
  vendor/golang.org/x/crypto/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/poly1305/sum_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm
