Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2020-11, with the labels that each got.

#151 Bug 1896697: Add ManagementState to sample CR
  deploy/02_kube-descheduler-operator.cr.yaml
  manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#154 Parse LogLevel operator spec setting
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/modules.txt
Labels: approved, lgtm

#155 bug 1902019: CSV: fix rbac for namespaces
  manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml
  manifests/4.5/cluster-kube-descheduler-operator.v4.5.0.clusterserviceversion.yaml
  manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml
  manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
