Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2020-10, with the labels that each got.

#141 bug 1884601: Drop kube-system role binding to extension-apiserver-authentication-reader
  deploy/02_clusterrole.yaml
  deploy/05_kube-system-rolebinding.yaml
  manifests/4.6/kube-system-rolebinding.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#142 Fix readme inconsistencies
  README.md
Labels: approved, lgtm

#143 Updating ose-cluster-kube-descheduler-operator builder & base images to be consistent with ART
  Dockerfile.rhel7
Labels: approved, lgtm

#144 Add BZ component name to OWNERS
  OWNERS
Labels: approved, lgtm

#145 Manifests 4.7
  README.md
  manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
  manifests/4.7/image-references
  manifests/4.7/kube-descheduler-operator.crd.yaml
  manifests/cluster-kube-descheduler-operator.package.yaml
Labels: approved, lgtm

#129 Bug 1874612: Add operatorhub icon to 4.4 manifest
  manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#147 bug 1887740: Extend olm.skipRange check to properly compare pre-release versions
  manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml
  manifests/4.5/cluster-kube-descheduler-operator.v4.5.0.clusterserviceversion.yaml
  manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml
  manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
Labels: approved, lgtm
