Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2020-03, with the labels that each got.

#92 bug 1810035: csv: change name to clusterkubedescheduleroperator.v4.4.0
  manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#93 bug 1810033: csv: change name to clusterkubedescheduleroperator.v4.4.0
  manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#95 Add support for actual descheduler strategy names in operator config
  README.md
  pkg/operator/target_config_reconciler.go
Labels: approved, lgtm, size/M

#94 Update operator description in CSV
  Dockerfile
  README.md
  manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#100 Update list of valid strategy names
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_test.go
Labels: approved, lgtm

#99 Revert changes to dockerfile
  Dockerfile
Labels: approved, lgtm

#103 Provide manifests for deploying the operator without OLM (for development only)
  README.md
  deploy/0000_00_kube-descheduler-operator.crd.yaml
  deploy/01_namespace.yaml
  deploy/02_clusterrole.yaml
  deploy/02_kube-descheduler-operator.cr.yaml
  deploy/03_clusterrolebinding.yaml
  deploy/04_serviceaccount.yaml
  deploy/05_deployment.yaml
  deploy/05_kube-system-rolebinding.yaml
Labels: approved, lgtm

#105 Bump to k8s 1.18.0 and library-go,api rebases
  go.mod
  go.sum
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/LICENSE
  vendor/github.com/openshift/api/build/v1/consts.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-svcat-apiserver-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_config.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/k8s.io/api/networking/v1beta1/generated.proto
  vendor/k8s.io/api/networking/v1beta1/types.go
  vendor/k8s.io/api/networking/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/port.go
  vendor/modules.txt
Labels: approved, lgtm

#106 [release-4.4] Bug 1817318: Add support for actual descheduler strategy names in operator config
  README.md
  pkg/operator/target_config_reconciler.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm
