Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2020-02, with the labels that each got.

#66 Bug 1797745: Setup bindata for resources
  README.md
  bindata/v4.1.0/kube-descheduler/configmap.yaml
  bindata/v4.1.0/kube-descheduler/deployment.yaml
  manifests/0000_00_kube-descheduler-operator.crd.yaml
  manifests/0000_01_kube-descheduler-operator.cr.yaml
  manifests/02_kube-descheduler-operator.cr.yaml
  pkg/apis/descheduler/v1beta1/types_descheduler.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/v410_00_assets/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/storage.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#68 Bug 1798220: Re-enable ability to pass additional flags to descheduler pod
  README.md
  manifests/0000_00_kube-descheduler-operator.crd.yaml
  pkg/apis/descheduler/v1beta1/types_descheduler.go
  pkg/apis/descheduler/v1beta1/zz_generated.deepcopy.go
  pkg/operator/target_config_reconciler.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#69 Bug 1798497: Update deployment generation statuses
  README.md
  manifests/0000_00_kube-descheduler-operator.crd.yaml
  manifests/02_kube-descheduler-operator.cr.yaml
  pkg/apis/descheduler/v1beta1/types_descheduler.go
  pkg/operator/operatorclient/interfaces.go
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#65 Bug 1798500: Add nodetaints strategy and refactor configmap string generation to use structs and marshalling
  README.md
  go.mod
  go.sum
  pkg/operator/target_config_reconciler.go
  vendor/modules.txt
  vendor/sigs.k8s.io/descheduler/LICENSE
  vendor/sigs.k8s.io/descheduler/pkg/api/doc.go
  vendor/sigs.k8s.io/descheduler/pkg/api/register.go
  vendor/sigs.k8s.io/descheduler/pkg/api/types.go
  vendor/sigs.k8s.io/descheduler/pkg/api/v1alpha1/defaults.go
  vendor/sigs.k8s.io/descheduler/pkg/api/v1alpha1/doc.go
  vendor/sigs.k8s.io/descheduler/pkg/api/v1alpha1/register.go
  vendor/sigs.k8s.io/descheduler/pkg/api/v1alpha1/types.go
  vendor/sigs.k8s.io/descheduler/pkg/api/v1alpha1/zz_generated.conversion.go
  vendor/sigs.k8s.io/descheduler/pkg/api/v1alpha1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/descheduler/pkg/api/v1alpha1/zz_generated.defaults.go
  vendor/sigs.k8s.io/descheduler/pkg/api/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/descheduler/pkg/descheduler/scheme/scheme.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#70 Bug 1799026: Re-add line to dynamically name the deployment policy configmap
  pkg/operator/target_config_reconciler.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#72 Bug 1800628: Switch to ghodss yaml package
  go.mod
  go.sum
  pkg/operator/target_config_reconciler.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#75 bug 1803139: Add appregistry delivery label to Dockerfile.rhel7
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#79 Bug 1798456: Make operator bundle for OML
  Dockerfile
  Dockerfile.rhel7
  manifests/01_namespace.yaml
  manifests/02_clusterrole.yaml
  manifests/02_kube-descheduler-operator.cr.yaml
  manifests/03_clusterrolebinding.yaml
  manifests/04_serviceaccount.yaml
  manifests/05_deployment.yaml
  manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml
  manifests/4.4/image-references
  manifests/4.4/kube-descheduler-operator.crd.yaml
  manifests/4.4/kube-system-rolebinding.yaml
  manifests/art.yaml
  manifests/cluster-kube-descheduler-operator.package.yaml
  metadata/annotations.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#81 Reference descheduler image in image-references
  manifests/4.4/image-references
Labels: approved, lgtm, size/XS

#85 Doozer requires spec.tags[].name to be dist-git names
  manifests/4.4/image-references
Labels: approved, lgtm, size/XS

#86 [release-4.4] bug 1805794: Doozer requires spec.tags[].name to be dist-git names
  manifests/4.4/image-references
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#88 image-references: descheduler is the right name for the image
  manifests/4.4/image-references
Labels: approved, lgtm, size/XS

#89 [release-4.4] bug 1805794: Descheduler image back to descheduler 4.4
  manifests/4.4/image-references
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#90 Set the CSV category to OpenShift Optional
  manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#91 [release-4.4] bug 1805794: Set the CSV category to OpenShift Optional
  manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
