Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2020-12, with the labels that each got.

#156 Add Profiles api and deprecate strategies/policy
  Makefile
  README.md
  bindata/v4.1.0/kube-descheduler/deployment.yaml
  bindata/v4.1.0/profiles/AffinityAndTaints.yaml
  bindata/v4.1.0/profiles/LifecycleAndUtilization.yaml
  bindata/v4.1.0/profiles/TopologyAndDuplicates.yaml
  deploy/02_clusterrole.yaml
  deploy/02_kube-descheduler-operator.cr.yaml
  manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
  manifests/4.7/kube-descheduler-operator.crd.yaml
  pkg/apis/descheduler/v1beta1/types_descheduler.go
  pkg/apis/descheduler/v1beta1/zz_generated.deepcopy.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/descheduler/observe_descheduler.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_test.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, do-not-merge/hold, lgtm

#157 Log an error when no profiles are set
  pkg/operator/target_config_reconciler.go
Labels: approved, lgtm

#159 Add support for IMAGE env var
  bindata/v4.1.0/kube-descheduler/deployment.yaml
  deploy/05_deployment.yaml
  manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, lgtm

#161 bug 1903188: Set --logging-format to text, empty value generates an error message
  bindata/v4.1.0/kube-descheduler/deployment.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#160 Update CSV with profiles and remove extra parameters
  manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
Labels: approved, lgtm

#162 Bug 1907375: Bump to 1.20
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/condition/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/request_deadline.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/delete.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/timeout.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/fake/generator_fake_for_type.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
