Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2020-09, with the labels that each got.

#125 bug 1874374: Add operatorhub icon to 4.5 manifest
  manifests/4.5/cluster-kube-descheduler-operator.v4.5.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#128 Bug 1874374: Fix bad paste of operatorhub icon
  manifests/4.5/cluster-kube-descheduler-operator.v4.5.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#130 Bug 1877856: Fix lowercasing of excludeOwnerKinds parameter
  pkg/operator/target_config_reconciler.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#131 Bug 1877892: Fix lowercasing in namespace & priorityThreshold parameters
  README.md
  pkg/operator/target_config_reconciler.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#132 bug 1879139: Be more verbose when the operator configuration is missing
  pkg/operator/operatorclient/interfaces.go
  pkg/operator/target_config_reconciler.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#133 bug 1879522: 4.6 manifests: bump minKubeVersion to 1.19.0
  manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#136 bug 1874374: icon: use png instead of svg
  manifests/4.5/cluster-kube-descheduler-operator.v4.5.0.clusterserviceversion.yaml
  manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#137 Bug 1879975: Move priorityclasses to correct apiGroup in SA
  manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#139 Bug 1880914: Change default log level to v=2
  bindata/v4.1.0/kube-descheduler/deployment.yaml
  pkg/operator/target_config_reconciler.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#140 bug 1881869: LowNodeUtilization: don't Atoi thresholdPriority params as other params
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#126 bug 1874380: Add operatorhub icon to 4.5 manifest
  manifests/4.5/cluster-kube-descheduler-operator.v4.5.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm
