Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2021-09, with the labels that each got.

#217 Bug 1997787: Rename DoNotEvictPodsWithPVC->EvictPodsWithPVC
  README.md
  bindata/assets/profiles/EvictPodsWithPVC.yaml
  manifests/4.9/cluster-kube-descheduler-operator.v4.9.0.clusterserviceversion.yaml
  manifests/4.9/kube-descheduler-operator.crd.yaml
  pkg/apis/descheduler/v1/types_descheduler.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#212 Bug 1995951: Fix olm.skipRange substitution
  manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml
  manifests/art.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#215 Bug 1991938: Update stored version to v1
  bindata/v4.1.0/kube-descheduler/v1-migration.yaml
  go.mod
  go.sum
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/v410_00_assets/bindata.go
  vendor/modules.txt
  vendor/sigs.k8s.io/kube-storage-version-migrator/LICENSE
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/register.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/types.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/clientset.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/scheme/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/scheme/register.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/generated_expansion.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/migration_client.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/storagestate.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/storageversionmigration.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#219 Clarify definition of local storage
  README.md
Labels: lgtm, approved

#220 Update rbac.authorization.k8s.io version in dev manifests
  deploy/02_clusterrole.yaml
  deploy/03_clusterrolebinding.yaml
Labels: lgtm, approved

#221 bug 1991938: Add missing RBAC for storageversionmigrations.migration.k8s.io
  manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#223 [release-4.8] Bug 1991938: Fix logic check in migration for 4.8
  pkg/operator/target_config_reconciler.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high
