Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2021-05, with the labels that each got.

#189 bug 1953707: Have olm.skipRange in csv correspond to search pattern in art.yaml
  manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
  manifests/art.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#193 bug 1955595: Remove CRD top dashes
  manifests/4.8/kube-descheduler-operator.crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#192 Bug 1959177: Update dev clusterrole manifest
  deploy/02_clusterrole.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#194 Transfer root-image configuration to this repository
  .ci-operator.yaml
Labels: approved, bugzilla/valid-bug, lgtm
