Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2021-04, with the labels that each got.

#177 Bug 1943224: Fix CSV olmSkipRange pattern for development
  manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
  manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#180 LifecycleAndUtilization profile: mention RemovePodsHavingTooManyRestarts is included as well
  README.md
Labels: approved, lgtm

#181 bug 1947771: descheduler operator: set resource requests
  manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#182 bug 1947771: descheduler operator: set resource requests [4.6, 4.7]
  manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml
  manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#185 bug 1948640: CRD: add missing subresources.status so the CRD's status can be updated
  manifests/4.8/kube-descheduler-operator.crd.yaml
  pkg/apis/descheduler/v1/types_descheduler.go
  pkg/apis/descheduler/v1beta1/types_descheduler.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#183 bug 1948267: descheduler operator: set resource requests
  manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml
  manifests/4.5/cluster-kube-descheduler-operator.v4.5.0.clusterserviceversion.yaml
  manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml
  manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#186 bug 1949972: servicemonitor: replace exported_namespace with pod_namespace
  bindata/v4.1.0/kube-descheduler/servicemonitor.yaml
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#187 Bug 1950409: Update v1beta1 references to v1
  README.md
  deploy/02_kube-descheduler-operator.cr.yaml
  manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml
  pkg/operator/target_config_reconciler.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#188 bug 1950232: manifests 4.8: set minKubeVersion to 1.21
  manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#184 Bug 1943224: Update olmSkipRange in 4.7 and 4.8 to remove dev pattern
  manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
  manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#190 bug 1943224: Have olm.skipRange in csv correspond to search pattern in art.yaml
  manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#191 Bug 1955595: Add DevPreviewLongLifecycle profile
  README.md
  bindata/v4.1.0/profiles/DevPreviewLongLifecycle.yaml
  manifests/4.8/kube-descheduler-operator.crd.yaml
  pkg/apis/descheduler/v1/types_descheduler.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/v410_00_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
