Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2022-05, with the labels that each got.

#234 Descheduler modes
  Makefile
  README.md
  manifests/4.11/kube-descheduler-operator.crd.yaml
  pkg/apis/descheduler/v1/types_descheduler.go
  pkg/apis/descheduler/v1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/typed/descheduler/v1/descheduler_client.go
  pkg/generated/clientset/versioned/typed/descheduler/v1/fake/fake_kubedescheduler.go
  pkg/operator/target_config_reconciler.go
Labels: lgtm, approved

#257 bug 2079805: manifests/deployment: comply to restricted pod security level
  Dockerfile.rhel7
  bindata/assets/kube-descheduler/deployment.yaml
  manifests/4.11/cluster-kube-descheduler-operator.v4.11.0.clusterserviceversion.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#260 bug 2091033: OSDOCS-3679: Clarifying which mode simulates vs evicts
  manifests/4.11/kube-descheduler-operator.crd.yaml
  pkg/apis/descheduler/v1/types_descheduler.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
