Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2022-01, with the labels that each got.

#235 Bug 2035986: Add default-container annotation
  bindata/assets/kube-descheduler/deployment.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#236 Bug 2037856: bump library go
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/client_metrics.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/workqueue_metrics.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/resource_cache.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/leaderelection/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/restclient/metrics.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#237 bug 2041581: Allow to set ciphers through observed config
  deploy/0000_00_kube-descheduler-operator.crd.yaml
  deploy/02_clusterrole.yaml
  manifests/4.10/cluster-kube-descheduler-operator.v4.10.0.clusterserviceversion.yaml
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/interfaces.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
  pkg/operator/target_config_reconciler.go
  vendor/github.com/openshift/library-go/pkg/operator/condition/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/listers.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_audit.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_cors.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#238 bug 2041466: Dockerfile: use make build instead of go build
  Dockerfile.rhel7
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#240 bug 2041326: Update the minKubeVersion in the CSV to reflect the v1.23 rebase
  manifests/4.10/cluster-kube-descheduler-operator.v4.10.0.clusterserviceversion.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#241 bug 2043240: Remove damemi from OWNERS
  OWNERS
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#242 bug 2042849: Dockerfile: use make build instead of go build
  Dockerfile
  Dockerfile.rhel7
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed
