Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2024-06, with the labels that each got.

#356 WRKLDS-1302: Promote DevPreviewLongLifecycle to LongLifecycle
  Makefile
  bindata/assets/profiles/LongLifecycle.yaml
  manifests/kube-descheduler-operator.crd.yaml
  pkg/apis/descheduler/v1/types_descheduler.go
  pkg/operator/target_config_reconciler.go
Labels: lgtm, approved, jira/valid-reference

#357 Update Dockerfiles and the testing instructions
  Dockerfile.metadata
  Dockerfile.rhel7
  README.md
  manifests/kube-descheduler-operator.crd.yaml
Labels: lgtm, approved

#358 operand: fix containers[].securityContext.readOnlyRootFilesystem field name
  bindata/assets/kube-descheduler/deployment.yaml
  deploy/05_deployment.yaml
  manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#359 operand: fix containers[].securityContext.readOnlyRootFilesystem field name
  bindata/assets/kube-descheduler/deployment.yaml
  deploy/05_deployment.yaml
  manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed

#360 Operator deployment: set an emptyDir /tmp
  Dockerfile.metadata
  Dockerfile.rhel7
  deploy/05_deployment.yaml
  manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
  test/e2e/bindata/assets/05_deployment.yaml
Labels: lgtm, approved

#362 NO-JIRA: Operator deployment: set an emptyDir /tmp
  Dockerfile.rhel7
  deploy/0000_00_kube-descheduler-operator.crd.yaml
  deploy/05_deployment.yaml
  manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
  test/e2e/bindata/assets/05_deployment.yaml
Labels: lgtm, approved, jira/valid-reference

#361 OCPBUGS-35569: Replace wildcards by explicit list of verbs
  bindata/assets/kube-descheduler/operandclusterrole.yaml
  deploy/02_clusterrole.yaml
  manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
  test/e2e/bindata/assets/03_clusterrole.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
