Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2024-05, with the labels that each got.

#346 wrong changes
  Dockerfile.metadata
Labels: lgtm, approved, ok-to-test, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#349 CSV: claim features.operators.openshift.io/disconnected as true
  manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#351 CSV: update replaced field to point to an existing version
  manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#350 fix: descheduler deployment wrong name
  pkg/operator/target_config_reconciler.go
Labels: lgtm, approved, ok-to-test
