Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2025-04, with the labels that each got.

#470 New DevKubeVirtRelieveAndMigrate profile
  README.md
  pkg/apis/descheduler/v1/types_descheduler.go
  pkg/generated/applyconfiguration/descheduler/v1/kubedescheduler.go
  pkg/generated/applyconfiguration/descheduler/v1/kubedeschedulerspec.go
  pkg/generated/applyconfiguration/descheduler/v1/kubedeschedulerstatus.go
  pkg/generated/applyconfiguration/descheduler/v1/profilecustomizations.go
  pkg/generated/applyconfiguration/internal/internal.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/typed/descheduler/v1/descheduler_client.go
  pkg/generated/clientset/versioned/typed/descheduler/v1/fake/fake_descheduler_client.go
  pkg/generated/clientset/versioned/typed/descheduler/v1/fake/fake_kubedescheduler.go
  pkg/generated/clientset/versioned/typed/descheduler/v1/kubedescheduler.go
  pkg/generated/informers/externalversions/descheduler/v1/kubedescheduler.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/listers/descheduler/v1/kubedescheduler.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_test.go
  pkg/operator/testdata/assets/relieveAndMigrateHighConfig.yaml
  pkg/operator/testdata/assets/relieveAndMigrateIncludedNamespace.yaml
  pkg/operator/testdata/assets/relieveAndMigrateLowConfig.yaml
  pkg/operator/testdata/assets/relieveAndMigrateMediumConfig.yaml
Labels: lgtm, approved

#471 CNTRLPLANE-260: devKubeVirtRelieveAndMigrate: enable EvictPodsWithPVC and EvictPodsWithLocalStorage by default
  README.md
  pkg/operator/target_config_reconciler.go
  pkg/operator/testdata/assets/relieveAndMigrateHighConfig.yaml
  pkg/operator/testdata/assets/relieveAndMigrateIncludedNamespace.yaml
  pkg/operator/testdata/assets/relieveAndMigrateLowConfig.yaml
  pkg/operator/testdata/assets/relieveAndMigrateMediumConfig.yaml
Labels: lgtm, approved, jira/valid-reference

#476 no-jira: no-op: to re-trigger build pipeline
  README.md
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#477 no-jira: no-op: to re-trigger build pipeline
  README.md
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#478 no-op: to re-trigger build pipeline
  README.md
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#479 no-jira: Revert "no-op: to re-trigger build pipeline"
  README.md
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#481 WRKLDS-1652: bump(bundle.Dockerfile): point to the latest images
  bundle.Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#482 no-jira: [tekton]: update bundle jobs
  .tekton/kube-descheduler-operator-bundle-4-18-pull-request.yaml
  .tekton/kube-descheduler-operator-bundle-4-18-push.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#483 no-jira: no-op: re-trigger pipeline
  README.md
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#484 no-jira: [tekton]: make the operator configs more up2date
  .tekton/kube-descheduler-operator-4-18-pull-request.yaml
  .tekton/kube-descheduler-operator-4-18-push.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-reference

#485 no-jira: bump(bundle.Dockerfile): point to the latest images
  bundle.Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#486 WRKLDS-1652: bump(kdo)=5.1.2
  manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#491 WRKLDS-1652: Extend fbc catalog with 5.1.1 and 5.1.2 releases and regen
  .tekton/images-mirror-set.yaml
  README.md
  v4.18/catalog-template.json
  v4.18/catalog/cluster-kube-descheduler-operator/catalog.json
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#494 Explicit error for DevKubeVirtRelieveAndMigrate without KubeVirt
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_test.go
Labels: lgtm, approved

#496 TargetConfigReconciler: extend TestSync with a condition check for DevKubeVirtRelieveAndMigrate operator profile
  pkg/operator/target_config_reconciler_test.go
Labels: lgtm, approved

#495 [e2e] test softtainter
  bindata/assets/kube-descheduler/softtaintervalidatingadmissionpolicy.yaml
  pkg/softtainter/softtainter.go
  test/e2e/bindata/assets/00_kube-descheduler-operator-crd.yaml
  test/e2e/bindata/assets/07_descheduler-operator.cr.devKubeVirtRelieveAndMigrate.yaml
  test/e2e/operator_test.go
Labels: lgtm, approved, tide/merge-method-squash

#497 no-jira: TargetConfigReconciler: extend TestSync with a condition check for DevKubeVirtRelieveAndMigrate operator profile
  bindata/assets/kube-descheduler/softtaintervalidatingadmissionpolicy.yaml
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_test.go
  pkg/softtainter/softtainter.go
  test/e2e/bindata/assets/00_kube-descheduler-operator-crd.yaml
  test/e2e/bindata/assets/07_descheduler-operator.cr.devKubeVirtRelieveAndMigrate.yaml
  test/e2e/operator_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#501 README: fix the new profile name
  README.md
Labels: lgtm, approved

#504 bundle: point to non-staging registry to use a snapshot for both staging and final release
  bundle.Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#505 bundle: point operator image to the latest one
  bundle.Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#506 Have the SoftTainter always deployed with KubeVirtRelieveAndMigrate
  README.md
  manifests/kube-descheduler-operator.crd.yaml
  pkg/apis/descheduler/v1/types_descheduler.go
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_test.go
  pkg/softtainter/softtainter.go
  pkg/softtainter/softtainter_test.go
  pkg/softtainter/testdata/policyNoRelieveAndMigrate.yaml
  test/e2e/bindata/assets/00_kube-descheduler-operator-crd.yaml
  test/e2e/bindata/assets/07_descheduler-operator.cr.devKubeVirtRelieveAndMigrate.yaml
Labels: lgtm, approved
