Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2025-03, with the labels that each got.

#459 OCPBUGS-52341: Add CPUPSIPressureUtilization ActualUtilizationProfile
  README.md
  pkg/apis/descheduler/v1/types_descheduler.go
  pkg/operator/target_config_reconciler.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#461 README: update the releases
  README.md
Labels: lgtm, approved

#447 RELEASE BLOCKER(March 1, 2025): add fbc-fips-check task to FBC pipeline
  .tekton/images-mirror-set.yaml
  .tekton/kube-descheduler-operator-fbc-4-18-pull-request.yaml
  .tekton/kube-descheduler-operator-fbc-4-18-push.yaml
Labels: needs-ok-to-test

#446 RELEASE BLOCKER(March 1, 2025): add fbc-fips-check task to FBC pipeline
  .tekton/images-mirror-set.yaml
  .tekton/kube-descheduler-operator-fbc-4-16-pull-request.yaml
  .tekton/kube-descheduler-operator-fbc-4-16-push.yaml
Labels: needs-ok-to-test

#465 no-jira: Sync tekton jobs to pick up the latest improvements
  .tekton/kube-descheduler-operator-fbc-4-18-pull-request.yaml
  .tekton/kube-descheduler-operator-fbc-4-18-push.yaml
Labels: approved, jira/valid-reference

#467 Extend the list of explictly protected namespaces with openshift namespace
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_test.go
  pkg/operator/testdata/assets/highNodeUtilization.yaml
  pkg/operator/testdata/assets/highNodeUtilizationMinimal.yaml
  pkg/operator/testdata/assets/highNodeUtilizationModerate.yaml
  pkg/operator/testdata/assets/lifecycleAndUtilizationEvictPvcPodsConfig.yaml
  pkg/operator/testdata/assets/lifecycleAndUtilizationPodLifeTimeCustomizationConfig.yaml
  pkg/operator/testdata/assets/lifecycleAndUtilizationPodLifeTimeWithThresholdPriorityClassNameConfig.yaml
  pkg/operator/testdata/assets/lifecycleAndUtilizationPodLifeTimeWithThresholdPriorityConfig.yaml
  pkg/operator/testdata/assets/longLifecycleWithLocalStorage.yaml
  pkg/operator/testdata/assets/lowNodeUtilizationHighConfig.yaml
  pkg/operator/testdata/assets/lowNodeUtilizationLowConfig.yaml
  pkg/operator/testdata/assets/lowNodeUtilizationMediumConfig.yaml
  pkg/operator/testdata/assets/softTopologyAndDuplicates.yaml
  pkg/operator/testdata/assets/topologyAndDuplicates.yaml
  vendor/github.com/openshift/client-go/config/applyconfigurations/utils.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_authentication.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusteroperator.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusterversion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_console.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_featuregate.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_imagecontentpolicy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_imagedigestmirrorset.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_imagetagmirrorset.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_infrastructure.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_ingress.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_network.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_node.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_oauth.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_operatorhub.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_project.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_scheduler.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1alpha1/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1alpha1/fake/fake_backup.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1alpha1/fake/fake_clusterimagepolicy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1alpha1/fake/fake_clustermonitoring.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1alpha1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1alpha1/fake/fake_imagepolicy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1alpha1/fake/fake_insightsdatagather.go
  vendor/github.com/openshift/client-go/route/applyconfigurations/utils.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/fake/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/fake/fake_route.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/fake/fake_route_client.go
  vendor/k8s.io/client-go/testing/fixture.go
  vendor/modules.txt
Labels: lgtm, approved
