Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2025-06, with the labels that each got.

#570 OCPBUGS-57338: error out on zeroed scheduling interval
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_test.go
  pkg/softtainter/softtainter.go
  pkg/softtainter/softtainter_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#583 OCPBUGS-56485: csv: add relatedImages
  manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#584 Backporting 4.20/master fixes to 4.19/KDO 5.2.0 release
  README.md
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_test.go
  pkg/operator/testdata/assets/relieveAndMigrateDefaults.yaml
  pkg/operator/testdata/assets/relieveAndMigrateDynamicThresholdsHigh.yaml
  pkg/operator/testdata/assets/relieveAndMigrateDynamicThresholdsLow.yaml
  pkg/operator/testdata/assets/relieveAndMigrateDynamicThresholdsMedium.yaml
  pkg/operator/testdata/assets/relieveAndMigrateHighConfig.yaml
  pkg/operator/testdata/assets/relieveAndMigrateIncludedNamespace.yaml
  pkg/operator/testdata/assets/relieveAndMigrateLowConfig.yaml
  pkg/operator/testdata/assets/relieveAndMigrateMediumConfig.yaml
  pkg/softtainter/softtainter.go
  pkg/softtainter/softtainter_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#585 bundle.Dockerfile: registry.stage.redhat.io -> registry.redhat.io
  bundle.Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed

#590 no-jira: .tekton: new task updates require IMAGE_URL and IMAGE_DIGEST envs to be present for apply-tags task
  .tekton/kube-descheduler-operator-4-19-pull-request.yaml
  .tekton/kube-descheduler-operator-4-19-push.yaml
  .tekton/kube-descheduler-operator-bundle-4-19-pull-request.yaml
  .tekton/kube-descheduler-operator-bundle-4-19-push.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#593 no-jira: .tekton: new task updates require IMAGE_URL and IMAGE_DIGEST envs to …
  .tekton/kube-descheduler-operator-4-16-pull-request.yaml
  .tekton/kube-descheduler-operator-4-16-push.yaml
  .tekton/kube-descheduler-operator-bundle-4-16-pull-request.yaml
  .tekton/kube-descheduler-operator-bundle-4-16-push.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#592 no-jira: .tekton: new task updates require IMAGE_URL and IMAGE_DIGEST envs to …
  .tekton/kube-descheduler-operator-4-18-pull-request.yaml
  .tekton/kube-descheduler-operator-4-18-push.yaml
  .tekton/kube-descheduler-operator-bundle-4-18-pull-request.yaml
  .tekton/kube-descheduler-operator-bundle-4-18-push.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-reference

#597 no-jira: no-op: retrigger pipeline
  README.md
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#611 readme: update releases
  README.md
Labels: lgtm, approved

#617 csv: add relatedImages
  manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug
