Repository openshift/cluster-kube-descheduler-operator, pull requests merged in 2025-05, with the labels that each got.

#507 Add an alert and an condition for RelieveAndMigrate without PSI
  README.md
  bindata/assets/kube-descheduler/psialert.yaml
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_test.go
  test/e2e/operator_test.go
Labels: lgtm, approved

#519 Add an alert and an condition for RelieveAndMigrate without PSI
  README.md
  bindata/assets/kube-descheduler/psialert.yaml
  pkg/operator/target_config_reconciler.go
  pkg/operator/target_config_reconciler_test.go
  test/e2e/operator_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#521 WRKLDS-1686: Prepare for 5.2.0 release
  README.md
  bundle.Dockerfile
  manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#523 bump(.tekton)=4.19
  .tekton/kube-descheduler-operator-4-19-pull-request.yaml
  .tekton/kube-descheduler-operator-4-19-push.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#526 bump(.tekton)=4.19
  .tekton/kube-descheduler-operator-bundle-4-19-pull-request.yaml
  .tekton/kube-descheduler-operator-bundle-4-19-push.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#531 no-jira: Update the latest tekton changes
  .tekton/kube-descheduler-operator-4-18-pull-request.yaml
  .tekton/kube-descheduler-operator-4-18-push.yaml
  .tekton/kube-descheduler-operator-bundle-4-18-pull-request.yaml
  .tekton/kube-descheduler-operator-bundle-4-18-push.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#532 no-jira: Update the latest tekton changes
  .tekton/kube-descheduler-operator-4-16-pull-request.yaml
  .tekton/kube-descheduler-operator-4-16-push.yaml
  .tekton/kube-descheduler-operator-bundle-4-16-pull-request.yaml
  .tekton/kube-descheduler-operator-bundle-4-16-push.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#533 Bump tekton to 4.20
  .tekton/kube-descheduler-operator-4-20-pull-request.yaml
  .tekton/kube-descheduler-operator-4-20-push.yaml
  .tekton/kube-descheduler-operator-bundle-4-20-pull-request.yaml
  .tekton/kube-descheduler-operator-bundle-4-20-push.yaml
Labels: lgtm, approved

#534 Update README.md
  README.md
Labels: lgtm, approved

#556 no-jira: csv: increase the 5.1 version pool
  manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
